---

- name: Install dependencies
  sudo: yes
  apt: "name={{ item }} state=installed update_cache=yes"
  with_items:
    - git
  when: ansible_os_family == 'Debian'

- name: Install dependencies
  sudo: yes
  yum: "name={{ item }} state=installed"
  with_items:
    - git
  when: ansible_os_family == 'RedHat'

- name: Allow running sudo without tty
  sudo: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults\s+requiretty'
    line: 'Defaults !requiretty'

- name: Remove devstack repo
  file: "path='{{ devstack_dir }}' state=absent"
  sudo: yes

- name: Clone devstack
  git: "repo='https://github.com/openstack-dev/devstack.git' dest='{{ devstack_dir }}' recursive=yes force=yes version='{{ devstack_version }}'"

- name: Create stack user
  sudo: yes
  command: "{{ devstack_dir }}/tools/create-stack-user.sh"
  environment:
    STACK_USER: "{{ devstack_user }}"

- name: Change ownerships of git repo to stack user
  sudo: yes
  file: "path='{{ devstack_dir }}' owner={{ devstack_user }} group={{ devstack_user }} recurse=true"

- name: Copy openstack config script
  template: "src='local.j2' dest='{{ devstack_dir }}/local.conf'"
  sudo: yes
  sudo_user: "{{ devstack_user }}"

- name: unstack before we stack
  sudo: yes
  shell: "{{ devstack_dir }}/unstack.sh || true"
  sudo_user: "{{ devstack_user }}"

  # path hack to work on centos 7
- name: Run openstack init script
  shell: "{{ devstack_dir }}/stack.sh" 
  args:
    executable: "/bin/bash"
  sudo: yes
  sudo_user: "{{ devstack_user }}"
  async: 3600 # 1 hour
  poll: 30

- name: Install firewalld package
  sudo: yes
  yum: pkg=firewalld state=present

- name: Ensure firewalld is running and enabled on boot
  sudo: yes
  service: name=firewalld state=started enabled=yes

- name: Add firewalld rules for ports from vars
  sudo: yes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: 'enabled'
  with_items: [27701, 5000, 8080, 80, 8774, 35357, 9696, 9292]

- name: Reload firewalld
  sudo: yes
  service:
    name: "firewalld"
    state: "reloaded"


