---
- name: Install git
  sudo: yes
  apt: name=git state=installed update_cache=yes

- name: Clone devstack
  git: "repo=https://github.com/openstack-dev/devstack.git dest='{{ stack_dir }}' recursive=no version='stable/juno'"

- name: Copy openstack config script
  template: "src='local.j2' dest='{{ stack_dir }}/local.conf'"

- name: Run openstack init script
  shell: "{{ stack_dir }}/stack.sh"
