---

- name: Install dependencies
  sudo: yes
  apt: "name={{ item }} state=installed update_cache=yes"
  with_items:
    - git
    - python-setuptools
    - python-pip
  when: ansible_os_family == 'Debian'

- name: Remove devstack repo
  file: "path='{{ devstack_dir }}' state=absent"
  sudo: yes

- name: Clone devstack
  git: "repo='https://github.com/openstack-dev/devstack.git' dest='{{ devstack_dir }}' recursive=yes force=yes version='{{ devstack_version }}'"

- name: Create stack user
  sudo: yes
  command: "{{ devstack_dir }}/tools/create-stack-user.sh"
  environment:
    STACK_USER: "{{ devstack_user }}"

- name: Change ownerships of git repo to stack user
  sudo: yes
  file: "path='{{ devstack_dir }}' owner={{ devstack_user }} group={{ devstack_user }} recurse=true"

- name: Copy openstack config script
  template: "src='local.j2' dest='{{ devstack_dir }}/local.conf'"
  sudo: yes
  sudo_user: "{{ devstack_user }}"

- name: unstack before we stack
  sudo: yes
  shell: "{{ devstack_dir }}/unstack.sh || true"
  sudo_user: "{{ devstack_user }}"

  # path hack to work on centos 7
- name: Run openstack init script
  command: "{{ devstack_dir }}/stack.sh"
  sudo: yes
  sudo_user: "{{ devstack_user }}"
  async: 3600 # 1 hour
  poll: 30
